version: "3.8"

services:
  # MySQL Database Service
  db:
    image: mysql:8.0
    container_name: mysql_express_db
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3308:3306" # Expose MySQL on host port 3308 (internal 3306)
    volumes:
      - mysql_express_data:/var/lib/  mysql

  # PhpMyAdmin Service
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_express
    restart: always
    environment:
      PMA_HOST: db # Connects to the 'db' service
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "8081:80" # Expose PhpMyAdmin on host port 8081
    depends_on:
      - db

  # Express.js Backend Service
  express_backend:
    build: ./app # Build from the Dockerfile in the 'app' directory
    container_name: express_app
    restart: always
    environment:
      PORT: ${PORT}
      DB_HOST: db # Connects to the 'db' service
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    ports:
      - "3000:3000" # Expose Express app on host port 3000 (internal 3000)
    depends_on:
      - db # Ensure database is ready before starting app

volumes:
  mysql_express_data:
